require("utilities.tree")
require("utilities.find")
require("utilities.vgit")
require("utilities.image")
require("utilities.indent")
require("utilities.quatro")
-- require("utilities.navic")
require("utilities.line")
require("utilities.colorizer")
require("utilities.telescope")
require("utilities.notify")
require("utilities.magma")
require("utilities.pretty-fold")
